### ISSUE TITLE
to know existing amounts of collections, and amount of new material coming in. collection amount, status, condition, health. Also collection health information.

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#545] opened 2021-03-23 16:51 UTC
As a Collection Manager, Director, Administrator I want to know the situation with collection amounts so that can plan ahead for future needs for new space and storage. for this I need to know existing amounts of collections, and amount of new material coming in. collection amount, status, condition, health. Also collection health information.

**Comment by SvMering** [comment] 2022-03-09 08:16
duplicate of https://github.com/DiSSCo/user-stories/issues/224

**Closed** 2022-03-09 08:17 UTC
Labels: duplicate, LS, ES, Metadata, Tools for reporting & statistics
