### ISSUE TITLE
access to impact stories and/or assessments

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#518] opened 2021-03-23 16:50 UTC
As a Policy maker I want to understand the value of DiSSCo so that can justify the national level investments in its operations for this I need access to impact stories and/or assessments

**Comment by SvMering** [comment] 2022-03-04 11:32
duplicate of https://github.com/DiSSCo/user-stories/issues/212

**Closed** 2022-03-04 11:33 UTC
Labels: LS, ES, Tools for data discovery, Metadata, Legal and policy framework, Tools for reporting & statistics
