### ISSUE TITLE
bulk data in comparable format, selective search and export tool,links to other databases (e.g. genbank, vegetation databases)

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#410] opened 2021-03-22 17:15 UTC
As a Researcher, Scientist I want to gather / compare / reuse data from individual "small scale" (e.g. single species) studies so that I can can do meta-analyses and find "large scale" general patterns

**Comment by SvMering** [comment] 2022-03-08 00:50
duplicate of https://github.com/DiSSCo/user-stories/issues/213

**Closed** 2022-03-08 00:54 UTC
Labels: User Category: Research (academic & non-academic), LS, Legal and policy framework, BiCIKL
