### ISSUE TITLE
footage for documentaries

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#605] opened 2021-06-22 10:01 UTC
As a journalist I want to film the (micro)fossil collections and interview scientists/curators so that I can get footage for documentaries for that I need "stories" related to the collections (e.g. historically important collections or somewhat fascinating material/species). 

Related user story #584

**Comment by SvMering** [comment] 2022-03-11 18:17
duplicate of https://github.com/DiSSCo/user-stories/issues/584

**Closed as completed by SvMering** 2022-03-11 18:17 UTC
Labels: duplicate, External (media & empowerment initiatives), User Org: Media company/organisation, ES, Metadata, Data integration
