### ISSUE TITLE
know the quality of the data

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#436] opened 2021-03-23 16:46 UTC
As a Researcher, Scientist I want to know the quality of the data provides so that incorporate it into an analysis for this I need it's up to date and certified (to some degree) by the institution publishing the data

**Comment by SvMering** [comment] 2022-03-09 22:52
duplicate of https://github.com/DiSSCo/user-stories/issues/322

**Closed by SvMering** 2022-03-09 22:52 UTC
Labels: duplicate, User Category: Research (academic & non-academic), LS, ES, Tools for data analysis
