### ISSUE TITLE
find type specimens of a fossil species or a mineral

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#592] opened 2021-03-25 14:54 UTC
As a Scientist I want to to find type specimens of a fossil species or a mineral so that I can verify and understand its taxonomic concept for this I need to be sure this name is understood uniformly.

**Comment by SvMering** [comment] 2022-03-11 16:42
duplicate of https://github.com/DiSSCo/user-stories/issues/287

**Closed by SvMering** 2022-03-11 16:42 UTC
Labels: duplicate, User Category: Research (academic & non-academic), ES, Tools for data discovery, Interoperability, Data integration, BiCIKL
