### ISSUE TITLE
(AI) algorithm based on a selection of geological specimens

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#599] opened 2021-06-21 12:42 UTC
As a Scientist I want to generate an generate an artificial intelligence (AI) algorithm based on a selection of geological specimens so that I can run the algorithm on images of other institutes to verify identifications and recover further specimens
under my species concept for this I need an AI toolbox to generate the AI algorithm.

**Comment by SvMering** [comment] 2022-03-11 17:26
duplicate of https://github.com/DiSSCo/user-stories/issues/253

**Closed as completed by SvMering** 2022-03-11 17:26 UTC
Labels: duplicate, ES, Tools for data analysis, Tools for identification
