### ISSUE TITLE
Verify the validity of a determination by inspecting the type material (mineral, fossil)

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#601] opened 2021-06-21 13:50 UTC
As a Scientist I want to verify the validity of a determination by inspecting the type material for that mineral / fossil so that I can confirm the valid identity of a mineral / fossil for this I need high quality images with different views (dorsal, ventral, detail shots etc...) and the metadata for the type specimens.

**Comment by SvMering** [comment] 2022-03-11 17:57
duplicate of https://github.com/DiSSCo/user-stories/issues/277

**Closed as completed by SvMering** 2022-03-11 17:57 UTC
Labels: duplicate, ES, 2D Images, 3D images, Tools for identification
