### ISSUE TITLE
high-res image / DNA to verify species identification; collection metadata (year, location, taxon interactions, co-occuring taxa)

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#429] opened 2021-03-23 16:44 UTC
As a Researcher, Scientist I want to find out if a taxon has vanished from part of its geographic range / ecological niche so that I can think of causes, consequences, countermeasures for this I need high-res image / DNA to verify species identification; collection metadata (year, location, taxon interactions, co-occuring taxa)

**Comment by SvMering** [comment] 2022-03-09 22:32
duplicate of https://github.com/DiSSCo/user-stories/issues/285

**Closed by SvMering** 2022-03-09 22:32 UTC
Labels: duplicate, LS, Tools for data discovery, Metadata, BiCIKL
