### ISSUE TITLE
to receive requests including all rock/mineral names involved

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#568] opened 2021-03-24 15:37 UTC
As a Curator I want to answer requests for specified objects so that I can search the collection and pull material for this I need to receive requests including all rock/mineral names involved

**Comment by SvMering** [comment] 2022-03-11 17:30
duplicate of https://github.com/DiSSCo/user-stories/issues/298

**Closed by SvMering** 2022-03-11 17:30 UTC
Labels: duplicate, User Category: Collection Management, ES, Metadata
