### ISSUE TITLE
interaction with various biological data publishing institutions and organisations,

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#516] opened 2021-03-23 16:50 UTC
As a Biodiversity Data Node Manager I want to a platform for the aggregation and retrieval of Biodiversity data (both collection and observation data) so that provide access to Biodiversity data and data analysis tools for this I need interaction with various biological data publishing institutions and organisations,

**Comment by SvMering** [comment] 2022-03-03 12:32
duplicate of https://github.com/DiSSCo/user-stories/issues/186

**Closed** 2022-03-03 12:33 UTC
Labels: LS, Tools for data analysis, Tools for data discovery, Interoperability, BiCIKL
