### ISSUE TITLE
know where else there are collections of this group

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#501] opened 2021-03-23 16:50 UTC
As a Collection Manager I want to start a digitizing project so that I can digitize a certain group of my collection; I like to do this internationally because of funding for this I need know where else there are collections of this group

**Comment by SvMering** [comment] 2022-03-10 19:54
duplicate of https://github.com/DiSSCo/user-stories/issues/221

**Closed by SvMering** 2022-03-10 19:54 UTC
Labels: duplicate, User Category: Research (academic & non-academic), LS, ES, Tools for data discovery, Metadata, Advanced search functionality
