### ISSUE TITLE
all collections by specific region for all rocks/minerals/fossils

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#600] opened 2021-06-21 12:45 UTC
As a Scientist I want to know all rocks/minerals/fossils (of a particular group) in an area so that I can make a checklist for this I need all collections by specific region.

**Comment by SvMering** [comment] 2022-03-11 17:48
duplicate of https://github.com/DiSSCo/user-stories/issues/278

**Closed as completed by SvMering** 2022-03-11 17:48 UTC
Labels: duplicate, ES, Metadata
