### ISSUE TITLE
evidence that DiSSCo's activities align with (e.g.) Sustainable Development Goals

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#531] opened 2021-03-23 16:51 UTC
As a Policy maker I want to find information on the contribution of DiSSCo to the international environmental policy agenda so that can justify national level investments in its operation for this I need evidence that DiSSCo's activities align with (e.g.) Sustainable Development Goals

**Comment by SvMering** [comment] 2022-03-04 11:22
duplicate of https://github.com/DiSSCo/user-stories/issues/211

**Closed** 2022-03-04 11:23 UTC
Labels: LS, ES, Data integration, Legal and policy framework, Tools for reporting & statistics
