### ISSUE TITLE
to select all DiSSCo records from a certain rock/mineral etc.

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#569] opened 2021-03-24 15:37 UTC
As a Scientist I want to cross-check data between specimens of the same rock/mineral etc. so that I can flag outliers and correct record data where necessary for this I need to select all DiSSCo records from a certain rock/mineral etc.

**Comment by SvMering** [comment] 2022-03-10 22:32
duplicate of https://github.com/DiSSCo/user-stories/issues/177

**Closed by SvMering** 2022-03-10 22:32 UTC
Labels: duplicate, User Category: Collection Management, ES, Annotation tools, Advanced search functionality
