### ISSUE TITLE
communication thread by rock type etc. / collector / geographic area

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#567] opened 2021-03-24 15:37 UTC
As a Curator I want to answer multiple requests on a specified group of rocks, minerals / collector / geographic area so that I can follow conversation about a request for this I need communication thread by rock type etc. / collector / geographic area

**Comment by SvMering** [comment] 2022-03-11 11:17
duplicate of https://github.com/DiSSCo/user-stories/issues/300

**Closed by SvMering** 2022-03-11 11:18 UTC
Labels: duplicate, User Category: Collection Management, ES, Tools for data discovery, Metadata, Tools for clustering requests
