### ISSUE TITLE
to know which institute holds specific collections

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#510] opened 2021-03-23 16:50 UTC
As a Collection Manager I want to connect a researcher to colleagues so that they can examine more collections for this I need to know which institute holds specific collections

**Comment by SvMering** [comment] 2022-03-09 08:05
duplicate of https://github.com/DiSSCo/user-stories/issues/222

**Closed** 2022-03-09 08:07 UTC
Labels: duplicate, LS, ES, Metadata, Data integration
