### ISSUE TITLE
learn about the rocks/minerals/fossils

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#603] opened 2021-06-21 14:41 UTC
As a Curious person I want to learn about the rocks/minerals/fossils that might be in my environment so that I can improve my 
knowledge on geology / mineralogy / palaeontology for this I need taxonomic fields, common names, geographic coordinates, species characteristics, images.

**Comment by SvMering** [comment] 2022-03-11 18:09
duplicate of https://github.com/DiSSCo/user-stories/issues/237

**Closed as completed by SvMering** 2022-03-11 18:09 UTC
Labels: duplicate, User Category: Education (academic & non-academic), ES, Data integration, Advanced search functionality
