### ISSUE TITLE
species names, images, distributions, habitats, needs, behaviour, ecological niches, relationships

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/user-stories#550] opened 2021-03-23 16:51 UTC
As a Teacher I want to learn about the variety of life and the relationships among species and their environment so that teach my students that we are all inter-connected and that Homo sapiens is not the best species on Earth for this I need species names, images, distributions, habitats, needs, behaviour, ecological niches, relationships

**Comment by SvMering** [comment] 2022-03-09 20:42
duplicate of https://github.com/DiSSCo/user-stories/issues/330

**Closed** 2022-03-09 20:42 UTC
Labels: duplicate, LS, 2D Images, Distribution data, Morphological data, Ecological data, BiCIKL
